### ISSUE TITLE
Missing indexes on version table

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#116]
#### Is your feature request related to a problem? Please describe.
Reviewing the database, there appears to be a missing indexes on the `version` table. There is no index on the `objectId` column, nor is there an index on the `versionId` column. 

When using versions, coms needs to fetch the latest version and the system queries where [`versionId` = ? and `objectId` = ?](https://github.com/bcgov/common-object-management-service/blob/855e5863d32a033306263c5fb2aad664739b299a/app/src/services/version.js#L140-L142)

When not using versions, coms needs to fetch the latest version and the system queries where [`objectId = ? and deleteMarker = false`](https://github.com/bcgov/common-object-management-service/blob/855e5863d32a033306263c5fb2aad664739b299a/app/src/services/version.js#L147-L151). 

This service function is used when [adding tags](https://github.com/bcgov/common-object-management-service/blob/855e5863d32a033306263c5fb2aad664739b299a/app/src/controllers/object.js#L179), [deleting tags](https://github.com/bcgov/common-object-management-service/blob/855e5863d32a033306263c5fb2aad664739b299a/app/src/controllers/object.js#L426) and [replace tags](https://github.com/bcgov/common-object-management-service/blob/855e5863d32a033306263c5fb2aad664739b299a/app/src/controllers/object.js#L666)

I created sample data with 100k rows to see the statistics. Without this index, the entire table needs to be scanned,

![image](https://user-images.githubusercontent.com/1844480/215958975-a2cdca96-8290-4715-85cf-82566640edf4.png)

and with index, only the index is scanned resulting in less data being read and quicker query time.

![image](https://user-images.githubusercontent.com/1844480/215959715-8723892d-b9b1-4ffa-98c1-acccfb7a99cd.png)

#### Describe the solution you'd like
At minimum, the project should add index on the `version` table on column `objectId`. Every object stored will have at least one version to associate tags and metadata. Since it is unlikely (and should be part of the design of the service) that deployments would store a large number of versions of the same document, adding an additional index or secondary index column including `versionId` would not bring gains and would only waste index storage space.

#### Describe alternatives you've considered
none

**Comment by TimCsaky** [comment]
thanks Phil. We're looking at this right away. great catch
