### ISSUE TITLE
Tag key and values have incorrect lengths in database

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#118]
#### Describe the bug

The tag table has incorrect lengths for the key and value columns. Base on your [wiki](https://github.com/bcgov/common-object-management-service/wiki/Metadata-Tag#tag) documenation and the [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html), a tag key can only be 128 Unicode characters in long and a tag value can be up to 256 Unicode characters long. 

The [database has lengths of 255](https://github.com/bcgov/common-object-management-service/blob/694b364e8fce08d7e67b2a79de6b24a33d4fceeb/app/src/db/models/tables/tag.js#L66-L67) for each of these columns.

**Comment by TimCsaky** [comment]
Please let me know if you need this fixed urgently.
We had planned to make this change sometime in the next week or so along with other database schema changes which we would prefer to do in one shot.
we will also want to update the validation layer as you pointed out previously.

**Comment by pbolduc** [comment]
This is not urgent and does not impact our deployment. I just wanted to have an explicit ticket to have it addressed. Thank you.

**Comment by TimCsaky** [comment]
Thanks Phil. By the way, we have done quite a few new features and minor adjustments to the COMS api endpoints lately.
After version 0.3 we modified COMS to support a multi-bucket set-up. so for example, there are some bucket related endpoints and `bucketId` is a new parameter that can be used in various places.
We will be updating our [API spec](https://coms-dev-master.apps.silver.devops.gov.bc.ca/api/v1/docs) in the next week.
If you are only using COMS with one bucket I would recommend pegging to v0.3
At some point we'd love to arrange a meeting to hear more about your implementation.

**Comment by jujaga** [comment]
This will be fixed in the 0.4 release.
