### ISSUE TITLE
Metadata documenation does not mention implemented limits on key and value lengths

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#119]
The [metadata](https://github.com/bcgov/common-object-management-service/wiki/Metadata-Tag#metadata) wiki page uses the same wording as the [AWS: Working with object metadata](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html) documenation. This documenation only calls out that:
> the user-defined metadata is limited to 2 KB in size. The size of user-defined metadata is measured by taking the sum of the number of bytes in the UTF-8 encoding of each key and value.

The database implementation puts a [limit of 255](https://github.com/bcgov/common-object-management-service/blob/694b364e8fce08d7e67b2a79de6b24a33d4fceeb/app/src/db/models/tables/metadata.js#L65-L66) for each the key and value. These limits do seem reasonable for the kind of service COMS is used for. It would be good to ensure the documenation reflects this design point. You may want to consider increasing the value length to match the tag value length for consistency.

This issue does not impact our use of COMS.

**Comment by jujaga** [comment]
Thanks for the discrepancy catch. I've added a maximum length annotation to the OpenAPI spec discussing the `x-amz-meta-*` header so that it expects a maximum length value of 255 to align with database implementation. This will appear in the v0.4.0 COMS release.
