### ISSUE TITLE
searchObjects returns 200 on success, but OpenAPI spec says it should return 201

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#120]
#### Describe the bug

I am trying to use the [OpenAPI Spec](https://github.com/bcgov/common-object-management-service/blob/master/app/src/docs/v1.api-spec.yaml) to create a client library to call COMS. The `searchObjects` operation is described to return [201](https://github.com/bcgov/common-object-management-service/blob/694b364e8fce08d7e67b2a79de6b24a33d4fceeb/app/src/docs/v1.api-spec.yaml#L277-L278), however, this should be [200](https://github.com/bcgov/common-object-management-service/blob/6edf9cdba3f7c0fccb987608f04808ca2d4c7a16/app/src/controllers/object.js#L703) as per the `searchObjects` controller code.

#### Expected behavior
The status codes returned by services should match the service contract.

**Comment by TimCsaky** [comment]
thanks.. good to know. we'll get that updated in the api spec asap.
