### ISSUE TITLE
Get object that does not exist returns 404, but the OpenAPI spec does not indicate 404 response code

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#122]
#### Describe the bug

When fetching a document that does not exist, the API will return response with status code 404 with a response body like this:

```json
{
   "type":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404",
   "title":"Not Found",
   "status":404,
   "detail":{
      "name":"NoSuchKey",
      "$fault":"client",
      "$metadata":{
         "httpStatusCode":404,
         "requestId":"174074B18D53A563",
         "attempts":1,
         "totalRetryDelay":0
      },
      "Code":"NoSuchKey",
      "Key":"a8de50e6-e319-49a1-9b77-a35fb750cd10",
      "BucketName":"traffic-ticket-dev",
      "Resource":"/traffic-ticket-dev/a8de50e6-e319-49a1-9b77-a35fb750cd10",
      "RequestId":"174074B18D53A563",
      "HostId":"349059a7-6f3b-4d6c-8e1d-723e065359b6",
      "message":"The specified key does not exist."
   }
}
```

However, the [readObject operation](https://github.com/bcgov/common-object-management-service/blob/694b364e8fce08d7e67b2a79de6b24a33d4fceeb/app/src/docs/v1.api-spec.yaml#L330-L387) in the OpenAPI spec does not define a 404 status code. Generated client libraries do not handle status codes that are not declared on an operation. It leaves it up to the developer to discover that kind of response codes to expect.

**Comment by jujaga** [comment]
Addressed in v0.4.0
