### ISSUE TITLE
Helm Chart cannot use a database if patroni.enabled=false

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#131]
#### Describe the bug
When using the Helm chart, if I set `patroni.enabled=false`, the chart cannot be deployed due to an error. I want to use a different HA database deployed separately from the COMS helm chart. We have a number of databases in our system, I do not want duplicate Patroni clusters which requires more resources and monitoring.

#### To Reproduce

1. Run

`helm upgrade coms ./common-object-management-service-0.0.8.tgz --install --values coms-values.yaml --set patroni.enabled=false`

2. See error,

Error: template: common-object-management-service/templates/deploymentconfig.yaml:43:27: executing "common-object-management-service/templates/deploymentconfig.yaml" at <include "patroni.fullname" .Subcharts.patroni>: error calling include: template: no template "patroni.fullname" associated with template "gotpl"

#### Expected behavior

I would be expected if not enabling patroni in the chart, I can reference an existing postgres database with appropriate credentials.

**Comment by jujaga** [comment]
Thanks for this report. We have plans to support non-Patroni dependency managed databases via the `dbSecretOverride` value in values.yaml and have added it into our backlog.

**Comment by jujaga** [comment]
Addressed in #158
