### ISSUE TITLE
OpenAPI spec has wrong response property for get object tagging

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#141]
#### Describe the bug

In the OpenAPI spec for the fetchTags operation (GET /object/tagging), the response is described to have a [`versionId`](https://github.com/bcgov/common-object-management-service/blob/c71a489f68ef8ac837e422896771ed3e50e8a8eb/app/src/docs/v1.api-spec.yaml#L801) property where I suspect, this property should be `objectId`.

I suspect the same is for get object metadata  [`versionId`](https://github.com/bcgov/common-object-management-service/blob/c71a489f68ef8ac837e422896771ed3e50e8a8eb/app/src/docs/v1.api-spec.yaml#L764) should be `objectId`.

**Comment by jujaga** [comment]
This should be addressed in the COMS v0.4.0 release. Closing this issue for now, but feel free to reopen if there are still discrepancies.
