### ISSUE TITLE
Objection query promises do not handle errors

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#151]
#### Describe the bug

We are seeing issues with client time outs. This is the same situation as closed issue #134. During high query activity searching for files, we see client time outs. The client's default time out is 100 seconds. Calls to the COMS service never returns in various cases. and because it never returns, nothing is logged in the COMS console of the pods. Tracking it down, the most likely situation would be unresolved promises. This lead me to look at where promises are being resolved. I am not very proficient JavaScript, so I may not correct.  

The problem definitely occurs when the system is under load. For example, when we are getting about 20-30 requests/second to COMS, we start to get time outs,

![image](https://user-images.githubusercontent.com/1844480/230484931-e8db3a60-0f28-46ae-922e-3314c619a876.png)

In the various services that query the database, the `then` handler does not provide a errorHandler parameter. By not handling the errors, the service could return SQL and other information about the application. See [Error handling](http://vincit.github.io/objection.js/recipes/error-handling.html) in the Objection documenation. 

Additionally it seems, the [`searchObjects`](https://github.com/bcgov/common-object-management-service/blob/5683ef4d45cee04759bc591e83f409b4947f0c10/app/src/controllers/object.js#L783-L785) controller function does not map the error using `errorToProblem` like other methods.

**Comment by pbolduc** [comment]
We see the COMS pod reports unhealthy during this time...

![image](https://user-images.githubusercontent.com/1844480/231820666-5156898b-0821-40b2-be7c-ff6beea127b4.png)

**Comment by TimCsaky** [comment]
Hey Phil.
I'm looking into these timeouts this week.
I suspect it may be a combination of sql queries and the way we handle unresolved javascript promises.
Are you able to let me know the resource allocation to your Patroni cluster (eg: cpu and memory, number of pods), or if you use a single postgres pod?

Is it mainly the searchObjects api call that gives timeouts under high load?

Thanks

**Comment by jujaga** [comment]
Closing this issue as the error conditions described are not repeatable. That being said, we did do an internal performance review pass and added a few indexes to the permission tables to improve lookup speed in #162 . Should a similar issue appear again in the upcoming COMS v0.4.1 release, please feel free to request this issue to be reopened or to file a new issue.
