### ISSUE TITLE
Database Connection Pool settings are hard coded

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#152]
#### Is your feature request related to a problem? Please describe.

It should be possible to adjust the database connection pool settings. They are hard coded [here](https://github.com/bcgov/common-object-management-service/blob/a4e5749cb66ccd9d5fb80658f582b55c54a24df2/app/knexfile.js#L55-L60)

**Comment by jujaga** [comment]
Addressed in #158
