### ISSUE TITLE
Keycloak Variables are required when Keycloak is disabled

### ISSUE THREAD

**Issue by dhaselhan** [bcgov/common-object-management-service#69]
#### Describe the bug
The Keycloak Server URL and Keycloak Realm are required to be set to open the documentation page, even when keycloak is not enabled.

#### To Reproduce
Do not set any Keycloak variables on the docker image
Run the image
Navigate to http://localhost:3000/api/v1/docs

You will receive the following error and a 500:
 {"component":"app","level":"error","message":"Configuration property \"keycloak.realm\" is not defined","stack":"Error: Configuration property \"keycloak.realm\" is not defined\n    at Config.get (/opt/app-root/src/app/node_modules/config/lib/config.js:182:11)\n    at getSpec (/opt/app-root/src/app/src/routes/v1/docs.js:12:114)\n    at /opt/app-root/src/app/src/routes/v1/docs.js:24:59\n    at Layer.handle [as handle_request] (/opt/app-root/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/app-root/src/app/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/opt/app-root/src/app/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/opt/app-root/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at /opt/app-root/src/app/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/opt/app-root/src/app/node_modules/express/lib/router/index.js:346:12)\n    at next (/opt/app-root/src/app/node_modules/express/lib/router/index.js:280:10)","timestamp":"2022-09-01T18:10:39.153Z"}

#### Expected behavior
When keycloak is not enabled, the app should not require Keycloak variables to be set

**Comment by jujaga** [comment]
Thank you for filing this issue @dhaselhan . We've addressed and applied the bugfix in #70 .

**Comment by dhaselhan** [comment]
Thanks for the fast fix! 👍
