### ISSUE TITLE
Uploads to Minio do not work due to content-length

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#81]
#### Describe the bug
I know this is documented in the [wiki](https://github.com/bcgov/common-object-management-service/wiki/Deployment-Guide#minio)

Trying to use Minio breaks because the content-length header is not present. This seems like it could be addressed by changing  from using `putObject` to `upload` from `@aws-sdk/lib-storage` as commented here:

https://github.com/aws/aws-sdk-js-v3/issues/2348#issuecomment-841002347

and in the upgrade guide from v2 to v3: https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md#s3-multipart-upload

#### To Reproduce

Point common-object-management-service to a Minio instance and upload a document.

#### Expected behavior
I should be able to use Minio for local development.

#### Additional context
I will see if I can find time this weekend to try my assertion that `upload` will work with minio.

**Comment by jujaga** [comment]
Integrated with #96
