### ISSUE TITLE
getAppAuthMode does not evaluate configuration values

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#86]
#### Describe the bug
The getAppAuthMode function does not evaluate the configuration. It only checks if the configuration is defined. This causes wrong evaluation if values are set but set to `false`.

https://github.com/bcgov/common-object-management-service/blob/a32d4a820f20f66e01833a3528a0fc5c73334faa/app/src/components/utils.js#L40-L48

In the above function, the code [tests if a config value exists](https://github.com/node-config/node-config/wiki/Common-Usage#testing-for-config-values) instead of [getting config](https://github.com/node-config/node-config/wiki/Common-Usage#using-config-values).

So if I define KC_ENABLED=false, the service starts up with OIDC configuration enabled. Since I do not have OIDC configuration values, the pod dies saying `Configuration property \"keycloak.clientId\" is not defined`

#### To Reproduce

1. Deploy service with KC_ENABLED=false set but do not set any other KC vars
2. See error at startup saying keycloak.clientId is not defined.

#### Expected behavior
If I configured KC_ENABLED=false, it should not expect keycloak configuration to be defined.

#### Screenshots
![msedge_1m1fZtonRb](https://user-images.githubusercontent.com/1844480/203616522-cbb6b7d2-42d5-4800-b4ef-075d4311400d.png)

![msedge_PFwJ0LSkYU](https://user-images.githubusercontent.com/1844480/203616542-1a290e6a-4f21-4c67-8d5d-6ae14a2610cc.png)

**Comment by TimCsaky** [comment]
You make a good point.. and it's a usability issue we want to resolve.
currently, the config values are parsed as strings. so `"false"` = true` 
it appears recent versions of the node-config library allow us to parse booleans.
We're going to look into this. but I expect it will be a v.0.5 change.

**Comment by pbolduc** [comment]
`config.has('basicAuth.enabled')` only checks if there is a value in `basicAuth.enabled`, but does not check the value. You could change it to:

`const basicAuth = config.has('basicAuth.enabled') && config.basicAuth.enabled === true`
