### ISSUE TITLE
createObjects operation returns null updatedBy when using basic auth

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#87]
#### Describe the bug
When creating an object with basic auth, the [updatedBy](https://github.com/bcgov/common-object-management-service/blob/0820b28d92de98aa78092387726eb4db93d4896f/app/src/docs/v1.api-spec.yaml#L1168) property comes back as null / nil. The [description](https://github.com/bcgov/common-object-management-service/blob/0820b28d92de98aa78092387726eb4db93d4896f/app/src/docs/v1.api-spec.yaml#L1171-L1174) of this property says as much. However, on the [DB-TimestampUserData](https://github.com/bcgov/common-object-management-service/blob/0820b28d92de98aa78092387726eb4db93d4896f/app/src/docs/v1.api-spec.yaml#L1147) object, these [properties](https://github.com/bcgov/common-object-management-service/blob/0820b28d92de98aa78092387726eb4db93d4896f/app/src/docs/v1.api-spec.yaml#L1149-L1153) are marked as required. Since these properties are marked required, generated client library will generate not nullable Guid property in C#. The response cannot be deserialized.

Also, the [createdBy](https://github.com/bcgov/common-object-management-service/blob/0820b28d92de98aa78092387726eb4db93d4896f/app/src/docs/v1.api-spec.yaml#L1155)'s [description](https://github.com/bcgov/common-object-management-service/blob/0820b28d92de98aa78092387726eb4db93d4896f/app/src/docs/v1.api-spec.yaml#L1158-L1161) says it should returned as null/nil as well. However, the value is returned as an empty Guid in this case.

```json
[
   {
      "id":"af243f31-fb63-4799-8c6d-e8fe6a52387a",
      "fieldName":"anyKey",
      "mimeType":"text/plain",
      "originalName":"integration.test",
      "metadata":{
         
      },
      "path":"af243f31-fb63-4799-8c6d-e8fe6a52387a",
      "public":false,
      "createdBy":"00000000-0000-0000-0000-000000000000",
      "createdAt":"2022-11-23T23:29:17.410Z",
      "active":true,
      "updatedBy":null,
      "updatedAt":"2022-11-23T23:29:17.409Z",
      "$metadata":{
         "httpStatusCode":200,
         "extendedRequestId":"1963f566b7c1b56c3b16ee9d3763e8734da19f78403042f7fa7122ecdd6ea118",
         "attempts":1,
         "totalRetryDelay":0
      },
      "ETag":"\"4ae71336e44bf9bf79d2752e234818a5\"",
      "ServerSideEncryption":"AES256"
   }
]
```

I would also expect the createdAt to be less or equal to updatedAt. It appears the object is updated one millisecond before it was created.

#### To Reproduce

1. Deploy service using BASIC AUTH
2. Create a document
3. View the response

#### Expected behavior
Since `createdBy` is set to Empty/Zero Guid, the `updatedBy` should be set the same way. Alternatively, these two properties should be nullable/not-required in the API specification.

**Comment by jujaga** [comment]
We have dropped the required flags on the `updatedBy` and `updatedAt` attributes from the `DB-TimestampUserData` schema on the OpenAPI spec. Will be in v0.4.0.
