### ISSUE TITLE
Suggestion: Add response types for operations using allOf

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#88]
#### Is your feature request related to a problem? Please describe.
The pattern for describing operation response makes client library generation problematic. For example [createObjects](https://github.com/bcgov/common-object-management-service/blob/0820b28d92de98aa78092387726eb4db93d4896f/app/src/docs/v1.api-spec.yaml#L88-L108). The generated code creates a number of "Anonymous" types. Thes types are ambiguous. createObjects returns a collection of Anonymous. Doesn't make the code easy to understand.  In other APIs I have used, the API spec would define an "operation response" type. This helps strongly typed language client generation like C#, Java or Typescript. Having usable client libraries for a variety of languages will reduce barriers to adoption of a common show case product.

![image](https://user-images.githubusercontent.com/1844480/203665754-ed0fc091-2436-45d0-818e-6c96cac0f81b.png)

The defined operation response schema object should not need a change to the response structure and should not break existing clients.

#### Describe the solution you'd like

For any operation that uses oneOf, use a convention that wraps the combined schemas into strongly type objects. For response objects, the convention could be similar to `operationName-Response`. The operations that appear to be impacted are:

- createObjects
- updateObject

#### Describe alternatives you've considered
I could modify your specification to make it work for me, but that is not maintainable or reusable. 

#### Additional context
Azure has all of their OpenAPI specs on github here: https://github.com/Azure/azure-rest-api-specs. They use these specifications to generate client libraries for .NET, Java, JavaScript/TypeScript, Python, Go, C++, C, Android and iOS.

**Comment by jujaga** [comment]
We have done a pass over all of the /component/schemas so that they all have a named title. Hopefully this helps with what you are describing and  that the objects are no longer anonymous. To be included in 0.4.0.
