### ISSUE TITLE
Deleting an object by id that does not exist returns 502 Bad Gateway error

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#89]
#### Describe the bug
Deleting an object by id that does not exist returns 502 Bad Gateway error.  I would probably expect an error of 404 Not Found.  

`502 Bad Gateway - The server was acting as a [gateway](https://en.wikipedia.org/wiki/Gateway_(telecommunications)) or proxy and received an invalid response from the upstream server.`

This doesn't make sense for an operation where I am trying to delete something that does not exist. We typically track client status code responses. Potentially having 5xx errors can throw out statistics.

There are valid reason why I may call delete multiple times on an object. For example, if my message broker delivers the same message again due to other failures processing the message.

In the off chance a 502 is an expected situation in this case, it should be documented in the openapi spec.

```json
{"type":"https://httpstatuses.com/502","title":"Unknown ObjectService Error","status":502,"detail":"NotFoundError"}
```

logs (the first one is the successful delete)

```
{"contentLength":"156","httpVersion":"1.1","ip":"::ffff:10.97.86.1","level":"http","message":"DELETE /api/v1/object/0a368c87-de24-497f-bb8e-fdd1d8be373f 200 201ms","method":"DELETE","path":"/api/v1/object/0a368c87-de24-497f-bb8e-fdd1d8be373f","responseTime":201,"statusCode":200,"timestamp":"2022-11-24T01:43:59.042Z"}
{"component":"authorization","function":"currentObject","level":"warn","message":"NotFoundError","timestamp":"2022-11-24T01:44:48.137Z"}
{"component":"errorToProblem","function":"errorToProblem","level":"error","message":"Unknown error calling ObjectService: NotFoundError","status":502,"timestamp":"2022-11-24T01:44:48.151Z"}
{"httpVersion":"1.1","ip":"::ffff:10.97.86.1","level":"http","message":"DELETE /api/v1/object/0a368c87-de24-497f-bb8e-fdd1d8be373f 502 19ms","method":"DELETE","path":"/api/v1/object/0a368c87-de24-497f-bb8e-fdd1d8be373f","responseTime":19,"statusCode":502,"timestamp":"2022-11-24T01:44:48.153Z"}
```

#### To Reproduce

1. Call on a non-existent object, here my Guid that should not be in your instance. `DELETE /api/v1/object/0a368c87-de24-497f-bb8e-fdd1d8be373f`
2. Observe the response status code

#### Expected behavior
I would expect a logical status code of 404 when trying to delete something "Not Found"

**Comment by pbolduc** [comment]
Should I deploy 0.3.0 to try to resolve this?

**Comment by jujaga** [comment]
> Should I deploy 0.3.0 to try to resolve this?

Yes. Right now v0.3.0 of COMS is the last stable release, so we recommend users to use that tag for now. You may choose to use master/latest, but we offer no stability guarantees there especially with all the parts moving around at the moment.

**Comment by pbolduc** [comment]
In version 0.3.0, the error 502 still appears to occur.

```
> common-object-management-service@0.3.0 start
> node ./bin/www
...
{"component":"errorToProblem","function":"errorToProblem","level":"error","message":"Unknown error calling ObjectService: NotFoundError","status":502,"timestamp":"2022-12-02T00:23:05.626Z"}
{"httpVersion":"1.1","ip":"::ffff:10.97.12.1","level":"http","message":"DELETE /api/v1/object/300f1a55-66f3-40dc-a1f6-326b05ccbbd2 502 21ms","method":"DELETE","path":"/api/v1/object/300f1a55-66f3-40dc-a1f6-326b05ccbbd2","responseTime":21,"statusCode":502,"timestamp":"2022-12-02T00:23:05.627Z"}
```

Still think if the v [here ](https://github.com/bcgov/common-object-management-service/blob/855e5863d32a033306263c5fb2aad664739b299a/app/src/controllers/object.js#L385) could detect `e.message === 'NotFoundError'` and return 404 instead of 502. But that should be only for this call [await objectService.delete(objId)](https://github.com/bcgov/common-object-management-service/blob/855e5863d32a033306263c5fb2aad664739b299a/app/src/controllers/object.js#L376)

**Comment by pbolduc** [comment]
> In version 0.3.0, the error 502 still appears to occur.
> 
> ```
> > common-object-management-service@0.3.0 start
> > node ./bin/www
> ...
> {"component":"errorToProblem","function":"errorToProblem","level":"error","message":"Unknown error calling ObjectService: NotFoundError","status":502,"timestamp":"2022-12-02T00:23:05.626Z"}
> {"httpVersion":"1.1","ip":"::ffff:10.97.12.1","level":"http","message":"DELETE /api/v1/object/300f1a55-66f3-40dc-a1f6-326b05ccbbd2 502 21ms","method":"DELETE","path":"/api/v1/object/300f1a55-66f3-40dc-a1f6-326b05ccbbd2","responseTime":21,"statusCode":502,"timestamp":"2022-12-02T00:23:05.627Z"}
> ```
> 
> Still think if the exception [here ](https://github.com/bcgov/common-object-management-service/blob/855e5863d32a033306263c5fb2aad664739b299a/app/src/controllers/object.js#L385) could detect `e.message === 'NotFoundError'` and return 404 instead of 502. But that should be only for this call [await objectService.delete(objId)](https://github.com/bcgov/common-object-management-service/blob/855e5863d32a033306263c5fb2aad664739b299a/app/src/controllers/object.js#L376)

In my service wrapper, I [catch this specific error](https://github.com/bcgov/jag-traffic-courts-online/blob/3185880eb8e62e5fc61f141d4d1728bf2b64cd9d/src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementService.cs#L81) and do not error out. In our app, I take the position if the caller wants to delete file X and it doesn't exist, then the delete is successful cause a file with the matching id does not exist.  But I do think if the COMS componet wants to return an error in this case, 404 Not Found makes better sense.

**Comment by jujaga** [comment]
Closing this as this issue references an older version of COMS that is no longer supported and not repeatable. That being said, we did apply some work in this commit to allow errors with status codes to respond as they are instead of being wrapped in a 502: 4dac9d4088141f7d580520e355780621acf65ba8
Please feel free to reopen or file a new issue if this has not been resolved.
