### ISSUE TITLE
Download via proxy does not appear to work

### ISSUE THREAD

**Issue by pbolduc** [bcgov/common-object-management-service#90]
#### Describe the bug
I am trying to re-download a file that has been uploaded. Since my S3 is not publicly available, I want to use the proxy mode. I am making the request like `https://{{ComsBaseUrl}}/api/v1/object/27f00551-9ace-48b5-a8fb-7e9efa9b4552?download=proxy`

but I am getting an error 

```json
{
    "name": "ValidationError",
    "message": "Validation Failed",
    "statusCode": 422,
    "error": "Unprocessable Entity",
    "details": {
        "query": [
            {
                "message": "\"download\" must be a boolean",
                "path": [
                    "download"
                ],
                "type": "boolean.base",
                "context": {
                    "label": "download",
                    "value": "proxy",
                    "key": "download"
                }
            }
        ]
    },
    "level": "debug"
}
```

The [download](https://github.com/bcgov/common-object-management-service/blob/aa07302743730b0aaa131d6e4c8d0164498f67bc/app/src/docs/v1.api-spec.yaml#L201) parameter is define as type [Query-Download](https://github.com/bcgov/common-object-management-service/blob/aa07302743730b0aaa131d6e4c8d0164498f67bc/app/src/docs/v1.api-spec.yaml#L852) which is an [DownloadMode](https://github.com/bcgov/common-object-management-service/blob/aa07302743730b0aaa131d6e4c8d0164498f67bc/app/src/docs/v1.api-spec.yaml#L1223-L1229) enumeration with values [proxy](https://github.com/bcgov/common-object-management-service/blob/aa07302743730b0aaa131d6e4c8d0164498f67bc/app/src/docs/v1.api-spec.yaml#L1227) or [url](https://github.com/bcgov/common-object-management-service/blob/aa07302743730b0aaa131d6e4c8d0164498f67bc/app/src/docs/v1.api-spec.yaml#L1228). In my test I used `proxy`. 

Even though The [download](https://github.com/bcgov/common-object-management-service/blob/aa07302743730b0aaa131d6e4c8d0164498f67bc/app/src/docs/v1.api-spec.yaml#L201) parameter says "Default behavior (undefined) will yield an HTTP 302 redirect to the S3 bucket via presigned URL", calling the service without a download parameter never returns and the request times out.

I was having problems with the generated client code, so I validated the behavior directly in postman.

#### To Reproduce

1. Make a GET request to (replace the GUID with something that exists) https://{{ComsBaseUrl}}/api/v1/object/27f00551-9ace-48b5-a8fb-7e9efa9b4552?download=proxy
2. observe the 422 status code with error message `"message": "\"download\" must be a boolean",`

#### Expected behavior
Attempting to download an object using its id and download=proxy should return the object stream in the response.

#### Screenshots
![image](https://user-images.githubusercontent.com/1844480/203684783-601eaf3f-be19-4c66-bd06-769ffa34a80a.png)

no download parameter

![image](https://user-images.githubusercontent.com/1844480/203685001-b7e64882-8611-408a-bf6c-951c8fdaf839.png)

**Comment by jujaga** [comment]
If you are running from the tagged v0.3 release, the API spec for this used to be a formal true/false boolean and not the enum. Due to the recent massive volume of re-engineering being done to support multiple buckets, the OpenAPI spec is significantly out of date with the implementation. We'll need to investigate this further once the dust settles a bit more. Thank you for raising this issue!

**Comment by pbolduc** [comment]
It seems we are running version 0.2.1 which comes from the Helm chart [appVersion](https://github.com/bcgov/common-object-management-service/blob/b7462a1bbe491c6c72141737eba2689f067f77a5/charts/coms/Chart.yaml#L46). It seems there is some missing steps on updating the Helm chart version with releases.  It is not clear the branching and versioning strategy being used.  Looking at the releases, there is a 0.3.0 but the helm chart version didn't get updated.

Is the master (surprised you have not been force/pressured to change this to `main`) branch just the `latest` version that may or may not be stable?  

The release numbering does not seem to have a logic semantic versioning scheme. releases 0.0.1 - 0.0.6 seem like "Pre-releases" but they are not created as Pre-release

![image](https://user-images.githubusercontent.com/1844480/203869308-d53a94c1-10dc-46b9-926c-1d07706b9807.png)


![image](https://user-images.githubusercontent.com/1844480/203869251-a99f39ee-a740-4171-a47e-9d015e688609.png)

**Comment by jujaga** [comment]
We have two release product lifecycles in this repo: 1) COMS API proper, and 2) COMS Helm Chart . While they address similar things as you need both to deploy, they're fundamentally different "things" and may operate on different release cadences, depending on what gets tuned and fixes. Unfortunately there isn't any real good way of showing the difference between those two kinds of releases on github, but one is for the API, and the other is for the Chart itself.

**Comment by pbolduc** [comment]
Upgrading the COMS version to 0.3.0 resolves this issue.
